<?php
 return array(
'DB_TYPE' => 'mysql',
'DB_HOST' => 'localhost',
'DB_NAME' => 'fy_project_manage',
'DB_USER' => 'chamaralabs',
'DB_PWD' => 'j83v72p6ub8q',
'DB_PORT' => '3306',
'DB_PREFIX' => 'pes_',
'PRIVATE_KEY' => 'de533c3bdd',
'USER_KEY' => '308d73a04c',
'ERROR_PROMPT' => '/Core/Theme/error.php',
'APP_GROUP_LIST' => 'Team',
'DEFAULT_GROUP' => 'Team',
'FILE_CACHE_PATH' => '/Temp',
'FILE_CACHE_TIME' => '1800',
'LOG_PATH' => '/log',
'LOG_DELETE' => '7',
'UPLOAD_PATH' => '/upload',
'SESSION_ID' => 'PESTESESSION',
);